version: "3.9"

services:

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    env_file:
      - ./api-gateway/.env
    depends_on:
      auth-service:
        condition: service_healthy
      blog-service:
        condition: service_healthy
      comment-service:
        condition: service_healthy
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
    #   interval: 10s
    #   timeout: 3s
    #   retries: 5
    #   start_period: 20s

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    env_file:
      - ./auth-service/.env
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
    #   interval: 10s
    #   timeout: 3s
    #   retries: 5
    #   start_period: 20s

  blog-service:
    build: ./blog-service
    container_name: blog-service
    ports:
      - "8082:8082"
    env_file:
      - ./blog-service/.env
    depends_on:
      auth-service:
        condition: service_healthy
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8082/health"]
    #   interval: 10s
    #   timeout: 3s
    #   retries: 5
    #   start_period: 20s

  comment-service:
    build: ./comment-service
    container_name: comment-service
    ports:
      - "8083:8083"
    env_file:
      - ./comment-service/.env
    depends_on:
      blog-service:
        condition: service_healthy
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8083/health"]
    #   interval: 10s
    #   timeout: 3s
    #   retries: 5
    #   start_period: 20s
